package(default_visibility=["//visibility:public"])

load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")

go_library(
  name = "hello",
  srcs = [
    "hello.go",
  ],
  importpath = "github.com/si-you/bazel-golang-examples/hello",
)
